# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

name: ML-DSA
type: signature
implementations:
  - name: ML-DSA-44
    claimed-nist-level: 2
    length-public-key: 1312
    length-secret-key: 2560
    length-signature: 2420
    kat-sha256: 9d4ae4ea0c1b56f96650838c7425cc2167a0754643b79a93bee28cb039ac2fc2
  - name: ML-DSA-65
    claimed-nist-level: 3
    length-public-key: 1952
    length-secret-key: 4032
    length-signature: 3309
    kat-sha256: b66d7de88a3bec2d7cf171a7a1198f6de47384e2a1dd3bf7d07432316a9a40f8
  - name: ML-DSA-87
    claimed-nist-level: 5
    length-public-key: 2592
    length-secret-key: 4896
    length-signature: 4627
    kat-sha256: 93029142bf62f67ae3df0d31c2fccf8c9fa1e61ab388048e1b3faeb9451a61ce
