# SPDX-License-Identifier: Apache-2.0

name: Bench
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [ "labeled" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  bench:
    permissions:
      contents: write
      pull-requests: write
    name: ${{ matrix.target.name }}
    strategy:
      fail-fast: true
      matrix:
       target:
        - system: rpi4
          name: Arm Cortex-A72 (Raspberry Pi 4) benchmarks
          bench_pmu: PMU
          archflags: -mcpu=cortex-a72 -DMLK_SYS_AARCH64_SLOW_BARREL_SHIFTER
          cflags: "-flto"
          bench_extra_args: ""
          only_no_opt: false
        - system: rpi5
          name: Arm Cortex-A76 (Raspberry Pi 5) benchmarks
          bench_pmu: PERF
          archflags: "-mcpu=cortex-a76 -march=armv8.2-a"
          cflags: "-flto"
          bench_extra_args: ""
          only_no_opt: false
        - system: a55
          name: Arm Cortex-A55 (Snapdragon 888) benchmarks
          bench_pmu: PERF
          archflags: "-mcpu=cortex-a55 -march=armv8.2-a"
          cflags: "-flto -static"
          bench_extra_args: -w exec-on-a55
          only_no_opt: false
        - system: bpi
          name: SpacemiT K1 8 (Banana Pi F3) benchmarks
          bench_pmu: PERF
          archflags: "-march=rv64imafdcv_zicsr_zifencei"
          cflags: "-static"
          bench_extra_args: -w exec-on-bpi
          cross_prefix: riscv64-unknown-linux-gnu-
          only_no_opt: true
    if: github.repository_owner == 'pq-code-package' && (github.event.label.name == 'benchmark' || github.ref == 'refs/heads/main')
    runs-on: self-hosted-${{ matrix.target.system }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/bench
        if: ${{ matrix.target.only_no_opt == 'false' }}
        with:
          name: ${{ matrix.target.name }} (opt)
          cflags: ${{ matrix.target.cflags }}
          archflags: ${{ matrix.target.archflags }}
          perf: ${{ matrix.target.bench_pmu }}
          store_results: ${{ github.repository_owner == 'pq-code-package' && github.ref == 'refs/heads/main' }}
          bench_extra_args: ${{ matrix.target.bench_extra_args }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          nix-shell: ${{ matrix.target.cross_prefix != '' && 'ci-cross' || 'ci-bench' }}
          cross_prefix: ${{ matrix.target.cross_prefix }}
          opt: true
      - uses: ./.github/actions/bench
        with:
          name: ${{ matrix.target.name }} (no-opt)
          cflags: ${{ matrix.target.cflags }}
          archflags: ${{ matrix.target.archflags }}
          perf: ${{ matrix.target.bench_pmu }}
          store_results: ${{ github.repository_owner == 'pq-code-package' && github.ref == 'refs/heads/main' }}
          bench_extra_args: ${{ matrix.target.bench_extra_args }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          nix-shell: ${{ matrix.target.cross_prefix != '' && 'ci-cross' || 'ci-bench' }}
          cross_prefix: ${{ matrix.target.cross_prefix }}
          opt: false
