# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

name: CBMC
permissions:
  contents: read
on:
  workflow_call:
  workflow_dispatch:

jobs:
  cbmc_44:
    name: CBMC (ML-DSA-44)
    if: ${{ github.repository_owner == 'pq-code-package' && !github.event.pull_request.head.repo.fork }}
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: ./.github/workflows/ci_ec2_reusable.yml
    with:
      name: CBMC (ML-DSA-44)
      ec2_instance_type: c7g.8xlarge
      ec2_ami: ubuntu-latest (custom AMI)
      ec2_ami_id: ami-0d7f502261b31b27f # aarch64, ubuntu-latest, 64g
      compile_mode: native
      opt: no_opt
      lint: false
      verbose: true
      functest: true
      kattest: false
      nistkattest: false
      acvptest: false
      cbmc: true
      cbmc_mldsa_mode: 2
    secrets: inherit
  cbmc_65:
    name: CBMC (ML-DSA-65)
    if: ${{ github.repository_owner == 'pq-code-package' && !github.event.pull_request.head.repo.fork }}
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: ./.github/workflows/ci_ec2_reusable.yml
    with:
      name: CBMC (ML-DSA-65)
      ec2_instance_type: c7g.8xlarge
      ec2_ami: ubuntu-latest (custom AMI)
      ec2_ami_id: ami-0d7f502261b31b27f # aarch64, ubuntu-latest, 64g
      compile_mode: native
      opt: no_opt
      lint: false
      verbose: true
      functest: true
      kattest: false
      nistkattest: false
      acvptest: false
      cbmc: true
      cbmc_mldsa_mode: 3
    secrets: inherit
  cbmc_87:
    name: CBMC (ML-DSA-87)
    if: ${{ github.repository_owner == 'pq-code-package' && !github.event.pull_request.head.repo.fork }}
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: ./.github/workflows/ci_ec2_reusable.yml
    with:
      name: CBMC (ML-DSA-87)
      ec2_instance_type: c7g.8xlarge
      ec2_ami: ubuntu-latest (custom AMI)
      ec2_ami_id: ami-0d7f502261b31b27f # aarch64, ubuntu-latest, 64g
      compile_mode: native
      opt: no_opt
      lint: false
      verbose: true
      functest: true
      kattest: false
      nistkattest: false
      acvptest: false
      cbmc: true
      cbmc_mldsa_mode: 5
    secrets: inherit
